[package]
name = "mini_transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16"
rand = "0.8"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serialization = ["serde"]
